//layouts lets you wrap all child pages inside some logic.
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // //this file is creating layouts for all the pages that we render, ran that page inside this.
  return (
  
    <html lang="en">
      <body className={inter.className}>
        <div className='p-4 border-b'>Medium website</div>
        
        {children}</body>
    </html>
  );
}
